In [2]:
import numpy as np
arr = np.array([10, 3, 2, 4, 5])

In [9]:
np.argsort(-arr)[:3]

array([0, 4, 3], dtype=int64)

In [7]:
np.argsort(arr)[:3]

array([3, 2, 4], dtype=int64)

In [10]:
arr

array([10,  3,  2,  4,  5])

In [11]:
306+31


337